"use client";

import { FormEvent, useEffect, useState } from "react";
import { Building2, CalendarClock, CheckCircle2, Loader2, LockKeyhole, RefreshCw, ShieldCheck, Store, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Tenant={id:string;slug:string;name:string;owner_name:string;owner_phone:string;ownerEmail:string;plan_code:string;subscription_status:"trialing"|"active"|"past_due"|"suspended"|"cancelled";trial_ends_at:string|null;subscription_due_at:string|null;grace_until:string|null;monthlyPrice:number;billing_notes:string;active:boolean;created_at:string;business_activity:"commerce"|"food"|"services";business_segment:string};
const statusLabel={trialing:"Período de teste",active:"Ativa",past_due:"Pagamento pendente",suspended:"Bloqueada",cancelled:"Cancelada"};
const activityLabel={commerce:"Comércio",food:"Alimentação",services:"Serviços"};
const segments={
  commerce:[['beauty_jewelry','Joias, beleza e cosméticos'],['fashion','Vestuário e moda'],['footwear','Calçados'],['general_retail','Comércio geral']],
  food:[['confectionery','Confeitaria'],['sweets_savories','Doces e salgados'],['bakery','Padaria'],['meals','Marmitas e refeições']],
  services:[['beauty_services','Beleza e estética'],['maintenance','Manutenção e serviços'],['professional_services','Serviços profissionais']],
} as const;
function BusinessFields({activity="commerce",segment="general_retail"}:{activity?:keyof typeof segments;segment?:string}){
  const [selected,setSelected]=useState<keyof typeof segments>(activity);
  const valid=segments[selected].some(([value])=>value===segment);
  return <><div className="field"><Label>Atividade</Label><select name="businessActivity" value={selected} onChange={e=>setSelected(e.target.value as keyof typeof segments)}><option value="commerce">Comércio</option><option value="food">Alimentação</option><option value="services">Serviços</option></select></div><div className="field"><Label>Segmento</Label><select name="businessSegment" defaultValue={valid?segment:segments[selected][0][0]} key={selected}>{segments[selected].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></div></>;
}
const money=(value:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(value||0);
const dateValue=(value:string|null)=>value?value.slice(0,10):"";

export function PlatformAdmin({api,notify}:{api:(action:string,payload?:Record<string,unknown>)=>Promise<any>;notify:(message:string)=>void}){
  const [tenants,setTenants]=useState<Tenant[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  async function load(){setLoading(true);try{const result=await api("platform_list_tenants");setTenants(result.tenants||[])}catch(e){notify(e instanceof Error?e.message:"Não foi possível carregar os lojistas") }finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const form=e.currentTarget;try{const result=await api("platform_create_tenant",Object.fromEntries(new FormData(form)));notify(result.message);form.reset();await load()}catch(e){notify(e instanceof Error?e.message:"Não foi possível criar a loja")}finally{setSaving(false)}}
  async function update(e:FormEvent<HTMLFormElement>,tenant:Tenant){e.preventDefault();const form=e.currentTarget;setSaving(true);try{const result=await api("platform_update_tenant",{id:tenant.id,...Object.fromEntries(new FormData(form))});notify(result.message);await load()}catch(e){notify(e instanceof Error?e.message:"Não foi possível atualizar a assinatura")}finally{setSaving(false)}}
  if(loading)return <div className="center"><Loader2 className="spin"/> Carregando administração…</div>;
  const paying=tenants.filter(t=>t.slug!=="wm-vendas"&&t.subscription_status==="active");
  const blocked=tenants.filter(t=>["suspended","cancelled"].includes(t.subscription_status));
  return <><div className="page-title"><div><small>ADMINISTRAÇÃO DO SAAS</small><h1>Lojistas e mensalidades</h1></div><Button variant="outline" onClick={()=>void load()}><RefreshCw/> Atualizar</Button></div>
    <div className="stats mini platform-stats"><article className="stat"><small>Lojas cadastradas</small><strong>{Math.max(0,tenants.length-1)}</strong></article><article className="stat"><small>Acessos ativos</small><strong>{paying.length}</strong></article><article className="stat"><small>Receita mensal prevista</small><strong>{money(paying.reduce((sum,item)=>sum+item.monthlyPrice,0))}</strong></article><article className="stat"><small>Bloqueadas</small><strong>{blocked.length}</strong></article></div>
    <section className="platform-grid"><form className="panel platform-create" onSubmit={create}><div className="panel-head"><div><small>NOVO CLIENTE</small><h2>Criar loja e acesso</h2></div><UserPlus/></div><div className="form"><div className="field full"><Label>Nome da loja</Label><Input name="storeName" required placeholder="Ex.: Bella Cosméticos"/></div><BusinessFields activity="commerce" segment="general_retail"/><div className="field full"><Label>Nome do responsável</Label><Input name="ownerName" required/></div><div className="field full"><Label>WhatsApp</Label><Input name="phone" inputMode="tel" required/></div><div className="field full"><Label>E-mail de acesso</Label><Input name="email" type="email" autoComplete="email" required/></div><div className="field full"><Label>Senha provisória</Label><Input name="password" type="password" minLength={8} autoComplete="new-password" required placeholder="Mínimo de 8 caracteres"/></div><div className="field"><Label>Plano</Label><select name="planCode" defaultValue="essencial"><option value="essencial">Essencial</option><option value="pro">Pro</option><option value="premium">Premium</option></select></div><div className="field"><Label>Mensalidade</Label><Input name="monthlyPrice" type="number" min="0" step="0.01" required/></div><div className="field full"><Label>Primeiro vencimento</Label><Input name="dueAt" type="date" required/></div><Button className="full" disabled={saving}>{saving?<Loader2 className="spin"/>:<LockKeyhole/>} Criar e liberar acesso</Button></div></form>
      <div className="platform-list"><section className="panel"><div className="panel-head"><div><small>CARTEIRA DE CLIENTES</small><h2>Controle de acesso</h2></div><ShieldCheck/></div>{tenants.map(tenant=><form className={`tenant-card tenant-${tenant.subscription_status}`} key={tenant.id} onSubmit={e=>void update(e,tenant)}><header><span><Building2/></span><div><b>{tenant.name}</b><small>{tenant.owner_name||"Responsável não informado"} · {tenant.ownerEmail||"Acesso pelo PIN"}</small><small>{activityLabel[tenant.business_activity]} · {segments[tenant.business_activity]?.find(([value])=>value===tenant.business_segment)?.[1]||tenant.business_segment}</small><a href={`/loja?loja=${tenant.slug}`} target="_blank" rel="noreferrer">/{tenant.slug}</a></div><em>{statusLabel[tenant.subscription_status]}</em></header><div className="tenant-billing"><BusinessFields activity={tenant.business_activity} segment={tenant.business_segment}/><label>Plano<select name="planCode" defaultValue={tenant.plan_code}><option value="founder">Fundador</option><option value="essencial">Essencial</option><option value="pro">Pro</option><option value="premium">Premium</option></select></label><label>Mensalidade<Input name="monthlyPrice" type="number" min="0" step="0.01" defaultValue={tenant.monthlyPrice}/></label><label>Vencimento<Input name="dueAt" type="date" defaultValue={dateValue(tenant.subscription_due_at)}/></label><label>Tolerância<select name="graceDays" defaultValue="3"><option value="0">Sem tolerância</option><option value="3">3 dias</option><option value="5">5 dias</option><option value="7">7 dias</option></select></label><label>Situação<select name="status" defaultValue={tenant.subscription_status} disabled={tenant.slug==="wm-vendas"}><option value="active">Ativa</option><option value="past_due">Pagamento pendente</option><option value="suspended">Bloqueada</option><option value="cancelled">Cancelada</option><option value="trialing">Período de teste</option></select>{tenant.slug==="wm-vendas"&&<input type="hidden" name="status" value="active"/>}</label><label className="notes">Observações<Input name="notes" defaultValue={tenant.billing_notes||""}/></label></div><footer><span><CalendarClock/> {tenant.subscription_due_at?`Vence em ${new Date(tenant.subscription_due_at).toLocaleDateString("pt-BR")}`:"Sem vencimento definido"}</span><Button size="sm" disabled={saving}><CheckCircle2/> Salvar situação</Button></footer></form>)}{!tenants.length&&<div className="team-empty"><Store/><b>Nenhum lojista cadastrado</b></div>}</section></div></section>
  </>;
}
