"use client";

import { FormEvent, useEffect, useState } from "react";
import { Check, Copy, ExternalLink, Loader2, MapPin, PackageCheck, Save, Send, ShoppingBag, Store, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type StoreSettings={slug:string;storeName:string;pixKey:string;pixHolderName:string;pixCity:string;whatsapp:string;storeEnabled:boolean;primaryColor:string;accentColor:string;slogan:string};
type StoreOrder={id:number;customerName:string;phone:string;deliveryType:string;address:string;total:number;status:string;paymentMethod:string;reservationExpiresAt:string;createdAt:string;items:{name:string;quantity:number;lineTotal:number}[]};
type StoreData={settings:StoreSettings;orders:StoreOrder[]};
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v||0);
const statusLabel:Record<string,string>={awaiting_payment:"Aguardando PIX",awaiting_approval:"Reserva solicitada",reserved:"Reserva aprovada",paid:"Pago",preparing:"Preparando",completed:"Concluído",cancelled:"Cancelado"};
const deliveryText=(order:StoreOrder)=>order.deliveryType==="retirada"?(order.status==="completed"?"Retirada concluída":order.status==="preparing"?"Pronto para retirada":"Aguardando preparação"):(order.status==="completed"?"Entregue":order.status==="preparing"?"Preparando para envio":"Entrega aguardando confirmação");

export function StoreAdmin({api,notify}:{api:(action:string,payload?:Record<string,unknown>)=>Promise<any>;notify:(message:string)=>void}){
  const [data,setData]=useState<StoreData|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  async function load(){try{setData(await api("store_admin"))}catch(e){notify(e instanceof Error?e.message:"Não foi possível carregar a loja")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);const form=new FormData(e.currentTarget);try{const result=await api("update_store_settings",{storeName:form.get("storeName"),slogan:form.get("slogan"),primaryColor:form.get("primaryColor"),accentColor:form.get("accentColor"),pixKey:form.get("pixKey"),pixHolderName:form.get("pixHolderName"),pixCity:form.get("pixCity"),whatsapp:form.get("whatsapp"),storeEnabled:form.get("storeEnabled")==="on"});notify(result.message);await load()}catch(err){notify(err instanceof Error?err.message:"Não foi possível salvar")}finally{setSaving(false)}}
  async function status(id:number,next:string){try{const result=await api("update_store_order_status",{id,status:next});notify(result.message);await load()}catch(e){notify(e instanceof Error?e.message:"Não foi possível atualizar")}}
  function whatsapp(order:StoreOrder,kind:"details"|"payment"|"delivery"="details"){const phone=`55${order.phone.replace(/\D/g,"").replace(/^55/,"")}`;const items=order.items.map(item=>`${item.quantity}x ${item.name} — ${money(item.lineTotal)}`).join("\n");const destination=order.deliveryType==="entrega"?`Entrega: ${order.address}`:"Retirada combinada com a vendedora";const base=`Olá, ${order.customerName}! 😊\n\n*WM Vendas — Pedido #${order.id}*\n${items}\n\n*Total: ${money(order.total)}*\n${destination}`;const payment=`Olá, ${order.customerName}! Tudo bem? 😊 Passando para lembrar do pagamento do pedido #${order.id}, no valor de ${money(order.total)}. Se já realizou o pagamento, pode desconsiderar. Obrigada! Walquíria Maia`;const delivery=`Olá, ${order.customerName}! Seu pedido #${order.id} foi atualizado: *${deliveryText(order)}*. ${destination}. Qualquer dúvida, estou à disposição. Walquíria Maia`;window.open(`https://wa.me/${phone}?text=${encodeURIComponent(kind==="payment"?payment:kind==="delivery"?delivery:base+"\n\nStatus: "+(statusLabel[order.status]||order.status))}`,"_blank")}
  if(loading)return <div className="center"><Loader2 className="spin"/> Carregando loja…</div>;
  if(!data)return null;
  const storePath=`/loja?loja=${data.settings.slug}`,storeUrl=`https://wm-vendas.vercel.app${storePath}`;
  return <><div className="page-title"><div><small>LOJA VIRTUAL</small><h1>Pedidos online</h1></div><a className="store-link-button" href={storePath}><ExternalLink/> Visualizar loja</a></div>
    <section className="store-admin-grid"><form className="panel store-settings" onSubmit={save}><div className="panel-head"><div><small>CONFIGURAÇÕES</small><h2>Marca, PIX e contato</h2></div><Store/></div><div className="form"><div className="field full"><Label>Nome da loja</Label><Input name="storeName" defaultValue={data.settings.storeName} required/></div><div className="field full"><Label>Slogan</Label><Input name="slogan" defaultValue={data.settings.slogan} maxLength={120}/></div><div className="field"><Label>Cor principal</Label><Input name="primaryColor" type="color" defaultValue={data.settings.primaryColor}/></div><div className="field"><Label>Cor de destaque</Label><Input name="accentColor" type="color" defaultValue={data.settings.accentColor}/></div><div className="field full"><Label>Chave PIX</Label><Input name="pixKey" defaultValue={data.settings.pixKey} placeholder="CPF, celular, e-mail ou chave aleatória" required/></div><div className="field"><Label>Nome do titular</Label><Input name="pixHolderName" defaultValue={data.settings.pixHolderName} maxLength={25} required/></div><div className="field"><Label>Cidade do titular</Label><Input name="pixCity" defaultValue={data.settings.pixCity} maxLength={15} required/></div><div className="field full"><Label>WhatsApp para comprovantes</Label><Input name="whatsapp" defaultValue={data.settings.whatsapp} inputMode="tel" placeholder="5599999999999" required/></div><label className="store-switch"><input type="checkbox" name="storeEnabled" defaultChecked={data.settings.storeEnabled}/><span>Loja aberta para novos pedidos</span></label><Button className="full" disabled={saving}>{saving?<Loader2 className="spin"/>:<Save/>} Salvar configurações</Button></div></form>
      <section className="panel online-orders"><div className="panel-head"><div><small>ÚLTIMOS PEDIDOS</small><h2>Compras das clientes</h2></div><ShoppingBag/></div>{data.orders.map(order=><article className="online-order" key={order.id}><header><div><b>Pedido #{order.id}</b><small>{new Date(order.createdAt).toLocaleString("pt-BR")} · {order.paymentMethod==="reservation"?"Reserva":"PIX"}</small></div><span className={`order-status status-${order.status}`}>{statusLabel[order.status]||order.status}</span></header><div className="order-customer"><b>{order.customerName}</b><a href={`https://wa.me/${order.phone}`} target="_blank">{order.phone}</a><small>{order.deliveryType==="entrega"?order.address:"Retirada com a vendedora"}</small></div><ul>{order.items.map((item,index)=><li key={index}><span>{item.quantity}x {item.name}</span><b>{money(item.lineTotal)}</b></li>)}</ul><div className="delivery-progress"><MapPin/><span>{deliveryText(order)}</span></div><div className="order-contact-actions"><Button size="sm" variant="outline" onClick={()=>whatsapp(order,"details")}><Send/> Enviar compra</Button>{["awaiting_payment","reserved"].includes(order.status)&&<Button size="sm" variant="outline" onClick={()=>whatsapp(order,"payment")}><Send/> Lembrar pagamento</Button>}<Button size="sm" variant="outline" onClick={()=>whatsapp(order,"delivery")}><Send/> Avisar cliente</Button></div><footer><strong>{money(order.total)}</strong><div>{order.status==="awaiting_approval"&&<><Button size="sm" onClick={()=>status(order.id,"reserved")}><Check/> Aprovar reserva</Button><Button size="sm" variant="outline" onClick={()=>status(order.id,"cancelled")}><X/> Recusar</Button></>}{order.status==="reserved"&&<><Button size="sm" onClick={()=>status(order.id,"paid")}><Check/> Confirmar pagamento</Button><Button size="sm" variant="outline" onClick={()=>status(order.id,"cancelled")}><X/> Cancelar</Button></>}{order.status==="awaiting_payment"&&<><Button size="sm" onClick={()=>status(order.id,"paid")}><Check/> Confirmar PIX</Button><Button size="sm" variant="outline" onClick={()=>status(order.id,"cancelled")}><X/> Cancelar</Button></>}{order.status==="paid"&&<Button size="sm" variant="outline" onClick={()=>status(order.id,"preparing")}><PackageCheck/> Preparar pedido</Button>}{order.status==="preparing"&&<Button size="sm" onClick={()=>status(order.id,"completed")}><Check/> {order.deliveryType==="entrega"?"Marcar entregue":"Confirmar retirada"}</Button>}</div></footer></article>)}{!data.orders.length&&<div className="store-order-empty"><ShoppingBag/><b>Nenhum pedido online ainda</b><span>Compartilhe o link da loja para começar.</span></div>}</section>
    </section><section className="share-store panel"><div><Copy/><span><b>Link exclusivo para compartilhar</b><small>{storeUrl}</small></span></div><Button variant="outline" onClick={()=>{navigator.clipboard.writeText(storeUrl);notify("Link copiado!")}}><Copy/> Copiar link</Button></section></>;
}
