begin;

create table if not exists public.wm_loans (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.wm_tenants(id) on delete restrict,
  customer_id bigint not null references public.wm_customers(id) on delete restrict,
  principal numeric(12,2) not null check (principal > 0),
  interest_rate numeric(8,4) not null default 0 check (interest_rate >= 0),
  interest_amount numeric(12,2) not null default 0 check (interest_amount >= 0),
  total_amount numeric(12,2) not null check (total_amount > 0),
  start_date date not null default current_date,
  due_date date not null,
  installments integer not null default 1 check (installments between 1 and 120),
  frequency text not null default 'unico' check (frequency in ('unico','semanal','quinzenal','mensal')),
  status text not null default 'active' check (status in ('active','paid','cancelled')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wm_loan_installments (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.wm_tenants(id) on delete restrict,
  loan_id bigint not null references public.wm_loans(id) on delete restrict,
  installment_number integer not null check (installment_number >= 1),
  due_date date not null,
  amount numeric(12,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','paid')),
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  unique (loan_id, installment_number)
);

create table if not exists public.wm_loan_payments (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.wm_tenants(id) on delete restrict,
  loan_id bigint not null references public.wm_loans(id) on delete restrict,
  installment_id bigint not null references public.wm_loan_installments(id) on delete restrict,
  customer_id bigint not null references public.wm_customers(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null default 'dinheiro',
  paid_at timestamptz not null default now(),
  notes text not null default '',
  created_at timestamptz not null default now()
);

alter table public.wm_loans enable row level security;
alter table public.wm_loan_installments enable row level security;
alter table public.wm_loan_payments enable row level security;
revoke all on public.wm_loans, public.wm_loan_installments, public.wm_loan_payments from anon, authenticated;
grant all on public.wm_loans, public.wm_loan_installments, public.wm_loan_payments to service_role;

create index if not exists wm_loans_tenant_status_idx on public.wm_loans(tenant_id,status);
create index if not exists wm_loans_customer_idx on public.wm_loans(tenant_id,customer_id,created_at desc);
create index if not exists wm_loan_installments_tenant_due_idx on public.wm_loan_installments(tenant_id,due_date,status);
create index if not exists wm_loan_installments_loan_idx on public.wm_loan_installments(loan_id,installment_number);
create index if not exists wm_loan_payments_tenant_paid_idx on public.wm_loan_payments(tenant_id,paid_at desc);
create index if not exists wm_loan_payments_loan_idx on public.wm_loan_payments(loan_id,installment_id,paid_at desc);
create index if not exists wm_loans_customer_fk_idx on public.wm_loans(customer_id);
create index if not exists wm_loan_payments_installment_fk_idx on public.wm_loan_payments(installment_id);
create index if not exists wm_loan_payments_customer_fk_idx on public.wm_loan_payments(customer_id);
create index if not exists wm_receivable_payments_customer_fk_idx on public.wm_receivable_payments(customer_id);

create or replace function public.wm_create_loan(
  p_tenant_id uuid,p_customer_id bigint,p_principal numeric,p_interest_rate numeric default 0,
  p_start_date date default current_date,p_first_due_date date default current_date,
  p_installments integer default 1,p_frequency text default 'unico',p_notes text default ''
) returns jsonb
language plpgsql set search_path to 'public','pg_temp' as $$
declare
  v_customer public.wm_customers%rowtype; v_loan_id bigint;
  v_interest numeric(12,2); v_total numeric(12,2); v_base numeric(12,2);
  v_amount numeric(12,2); v_due date; v_i integer;
begin
  if p_tenant_id is null or p_customer_id is null then raise exception 'Cliente inválido.'; end if;
  if p_principal is null or p_principal <= 0 then raise exception 'Informe um valor de empréstimo válido.'; end if;
  if p_interest_rate is null or p_interest_rate < 0 then raise exception 'Informe uma taxa de juros válida.'; end if;
  if p_installments is null or p_installments < 1 or p_installments > 120 then raise exception 'Quantidade de parcelas inválida.'; end if;
  if p_frequency not in ('unico','semanal','quinzenal','mensal') then raise exception 'Periodicidade inválida.'; end if;
  if p_first_due_date is null or p_start_date is null then raise exception 'Informe as datas do empréstimo.'; end if;
  if p_frequency='unico' and p_installments<>1 then raise exception 'Empréstimo único deve ter 1 parcela.'; end if;
  select * into v_customer from public.wm_customers where tenant_id=p_tenant_id and id=p_customer_id;
  if not found then raise exception 'Cliente não encontrado.'; end if;
  v_interest:=round(p_principal*p_interest_rate/100,2); v_total:=round(p_principal+v_interest,2); v_base:=round(v_total/p_installments,2);
  insert into public.wm_loans(tenant_id,customer_id,principal,interest_rate,interest_amount,total_amount,start_date,due_date,installments,frequency,status,notes)
  values(p_tenant_id,p_customer_id,round(p_principal,2),round(p_interest_rate,4),v_interest,v_total,p_start_date,p_first_due_date,p_installments,p_frequency,'active',coalesce(p_notes,'')) returning id into v_loan_id;
  for v_i in 1..p_installments loop
    if p_frequency='unico' then v_due:=p_first_due_date;
    elsif p_frequency='semanal' then v_due:=p_first_due_date+((v_i-1)*7);
    elsif p_frequency='quinzenal' then v_due:=p_first_due_date+((v_i-1)*15);
    else v_due:=(p_first_due_date+make_interval(months=>v_i-1))::date; end if;
    v_amount:=case when v_i<p_installments then v_base else round(v_total-(v_base*(p_installments-1)),2) end;
    insert into public.wm_loan_installments(tenant_id,loan_id,installment_number,due_date,amount)
    values(p_tenant_id,v_loan_id,v_i,v_due,v_amount);
  end loop;
  insert into public.wm_cash_entries(tenant_id,kind,category,description,amount,payment_method,occurred_at,source_type,source_id)
  values(p_tenant_id,'expense','Empréstimo concedido','Empréstimo para '||v_customer.name,round(p_principal,2),'dinheiro',p_start_date::timestamptz,'loan',v_loan_id);
  return jsonb_build_object('loanId',v_loan_id,'customerId',v_customer.id,'customerName',v_customer.name,'principal',round(p_principal,2),'interestRate',round(p_interest_rate,4),'interestAmount',v_interest,'totalAmount',v_total,'installments',p_installments,'firstDueDate',p_first_due_date,'status','active');
end; $$;

revoke all on function public.wm_create_loan(uuid,bigint,numeric,numeric,date,date,integer,text,text) from public,anon,authenticated;
grant execute on function public.wm_create_loan(uuid,bigint,numeric,numeric,date,date,integer,text,text) to service_role;

create or replace function public.wm_record_loan_payment(
  p_tenant_id uuid,p_installment_id bigint,p_amount numeric,p_payment_method text default 'dinheiro',
  p_paid_at timestamptz default now(),p_notes text default ''
) returns jsonb
language plpgsql set search_path to 'public','pg_temp' as $$
declare
  v_installment public.wm_loan_installments%rowtype; v_loan public.wm_loans%rowtype;
  v_customer public.wm_customers%rowtype; v_paid numeric(12,2); v_remaining numeric(12,2);
  v_payment_id bigint; v_cash_id bigint; v_status text;
begin
  if p_amount is null or p_amount<=0 then raise exception 'Informe um valor de pagamento válido.'; end if;
  select * into v_installment from public.wm_loan_installments where tenant_id=p_tenant_id and id=p_installment_id for update;
  if not found then raise exception 'Parcela do empréstimo não encontrada.'; end if;
  select * into v_loan from public.wm_loans where tenant_id=p_tenant_id and id=v_installment.loan_id for update;
  if not found then raise exception 'Empréstimo não encontrado.'; end if;
  if v_loan.status='cancelled' then raise exception 'Este empréstimo está cancelado.'; end if;
  select * into v_customer from public.wm_customers where tenant_id=p_tenant_id and id=v_loan.customer_id;
  if not found then raise exception 'Cliente não encontrado.'; end if;
  select coalesce(sum(amount),0) into v_paid from public.wm_loan_payments where tenant_id=p_tenant_id and installment_id=v_installment.id;
  v_remaining:=round(v_installment.amount-v_paid,2);
  if v_remaining<=0 then raise exception 'Esta parcela já está quitada.'; end if;
  if round(p_amount,2)>v_remaining then raise exception 'O pagamento não pode ser maior que o saldo da parcela.'; end if;
  insert into public.wm_loan_payments(tenant_id,loan_id,installment_id,customer_id,amount,payment_method,paid_at,notes)
  values(p_tenant_id,v_loan.id,v_installment.id,v_loan.customer_id,round(p_amount,2),coalesce(nullif(trim(p_payment_method),''),'dinheiro'),coalesce(p_paid_at,now()),coalesce(p_notes,'')) returning id into v_payment_id;
  v_paid:=round(v_paid+round(p_amount,2),2); v_remaining:=round(v_installment.amount-v_paid,2);
  if v_remaining<=0 then update public.wm_loan_installments set status='paid',paid_at=coalesce(p_paid_at,now()) where id=v_installment.id and tenant_id=p_tenant_id; end if;
  if not exists(select 1 from public.wm_loan_installments li where li.tenant_id=p_tenant_id and li.loan_id=v_loan.id and li.status='pending') then
    update public.wm_loans set status='paid',updated_at=now() where tenant_id=p_tenant_id and id=v_loan.id; v_status:='paid';
  else v_status:='active'; end if;
  insert into public.wm_cash_entries(tenant_id,kind,category,description,amount,payment_method,occurred_at,source_type,source_id)
  values(p_tenant_id,'income','Recebimento de empréstimo','Parcela '||v_installment.installment_number||' — '||v_customer.name,round(p_amount,2),coalesce(nullif(trim(p_payment_method),''),'dinheiro'),coalesce(p_paid_at,now()),'loan_payment',v_payment_id) returning id into v_cash_id;
  return jsonb_build_object('loanPaymentId',v_payment_id,'cashEntryId',v_cash_id,'loanId',v_loan.id,'installmentId',v_installment.id,'customerId',v_customer.id,'customerName',v_customer.name,'installmentNumber',v_installment.installment_number,'installmentAmount',v_installment.amount,'paidAmount',round(p_amount,2),'paidTotal',v_paid,'remainingAmount',greatest(v_remaining,0),'dueDate',v_installment.due_date,'paidAt',coalesce(p_paid_at,now()),'paymentMethod',coalesce(nullif(trim(p_payment_method),''),'dinheiro'),'status',v_status);
end; $$;

revoke all on function public.wm_record_loan_payment(uuid,bigint,numeric,text,timestamptz,text) from public,anon,authenticated;
grant execute on function public.wm_record_loan_payment(uuid,bigint,numeric,text,timestamptz,text) to service_role;

commit;