begin;

create table if not exists public.wm_loan_policies (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null unique references public.wm_tenants(id) on delete restrict,
  grace_days integer not null default 0 check (grace_days between 0 and 365),
  late_penalty_rate numeric(8,4) not null default 0 check (late_penalty_rate >= 0 and late_penalty_rate <= 100),
  late_interest_daily_rate numeric(8,6) not null default 0 check (late_interest_daily_rate >= 0 and late_interest_daily_rate <= 10),
  late_interest_compound boolean not null default false,
  late_charge_cap_rate numeric(8,4) not null default 100 check (late_charge_cap_rate >= 0 and late_charge_cap_rate <= 1000),
  reminder_days integer[] not null default array[7,3,1,0],
  updated_at timestamptz not null default now()
);

alter table public.wm_loans add column if not exists grace_days integer not null default 0;
alter table public.wm_loans add column if not exists late_penalty_rate numeric(8,4) not null default 0;
alter table public.wm_loans add column if not exists late_interest_daily_rate numeric(8,6) not null default 0;
alter table public.wm_loans add column if not exists late_interest_compound boolean not null default false;
alter table public.wm_loans add column if not exists late_charge_cap_rate numeric(8,4) not null default 100;

alter table public.wm_loan_policies enable row level security;
revoke all on public.wm_loan_policies from anon, authenticated;
grant all on public.wm_loan_policies to service_role;
create index if not exists wm_loan_policies_tenant_idx on public.wm_loan_policies(tenant_id);

create or replace function public.wm_get_loan_policy(p_tenant_id uuid)
returns jsonb language plpgsql set search_path to 'public','pg_temp' as $$
declare v public.wm_loan_policies%rowtype;
begin
  insert into public.wm_loan_policies(tenant_id) values(p_tenant_id) on conflict (tenant_id) do nothing;
  select * into v from public.wm_loan_policies where tenant_id=p_tenant_id;
  return jsonb_build_object('id',v.id,'tenantId',v.tenant_id,'graceDays',v.grace_days,'latePenaltyRate',v.late_penalty_rate,'lateInterestDailyRate',v.late_interest_daily_rate,'lateInterestCompound',v.late_interest_compound,'lateChargeCapRate',v.late_charge_cap_rate,'reminderDays',v.reminder_days);
end; $$;

create or replace function public.wm_upsert_loan_policy(
  p_tenant_id uuid,p_grace_days integer default 0,p_late_penalty_rate numeric default 0,
  p_late_interest_daily_rate numeric default 0,p_late_interest_compound boolean default false,
  p_late_charge_cap_rate numeric default 100,p_reminder_days integer[] default array[7,3,1,0]
) returns jsonb language plpgsql set search_path to 'public','pg_temp' as $$
declare v public.wm_loan_policies%rowtype;
begin
  if p_grace_days < 0 or p_grace_days > 365 then raise exception 'Carência inválida.'; end if;
  if p_late_penalty_rate < 0 or p_late_penalty_rate > 100 then raise exception 'Multa inválida.'; end if;
  if p_late_interest_daily_rate < 0 or p_late_interest_daily_rate > 10 then raise exception 'Juros diários inválidos.'; end if;
  if p_late_charge_cap_rate < 0 or p_late_charge_cap_rate > 1000 then raise exception 'Limite de encargos inválido.'; end if;
  if p_reminder_days is null or array_length(p_reminder_days,1) is null then raise exception 'Configure ao menos um aviso.'; end if;
  insert into public.wm_loan_policies(tenant_id,grace_days,late_penalty_rate,late_interest_daily_rate,late_interest_compound,late_charge_cap_rate,reminder_days,updated_at)
  values(p_tenant_id,p_grace_days,round(p_late_penalty_rate,4),round(p_late_interest_daily_rate,6),coalesce(p_late_interest_compound,false),round(p_late_charge_cap_rate,4),p_reminder_days,now())
  on conflict (tenant_id) do update set grace_days=excluded.grace_days,late_penalty_rate=excluded.late_penalty_rate,late_interest_daily_rate=excluded.late_interest_daily_rate,late_interest_compound=excluded.late_interest_compound,late_charge_cap_rate=excluded.late_charge_cap_rate,reminder_days=excluded.reminder_days,updated_at=now()
  returning * into v;
  return jsonb_build_object('id',v.id,'tenantId',v.tenant_id,'graceDays',v.grace_days,'latePenaltyRate',v.late_penalty_rate,'lateInterestDailyRate',v.late_interest_daily_rate,'lateInterestCompound',v.late_interest_compound,'lateChargeCapRate',v.late_charge_cap_rate,'reminderDays',v.reminder_days);
end; $$;

create or replace function public.wm_calculate_loan_installment_due(p_tenant_id uuid,p_installment_id bigint,p_as_of_date date default current_date)
returns jsonb language plpgsql set search_path to 'public','pg_temp' as $$
declare
  v_i public.wm_loan_installments%rowtype; v_l public.wm_loans%rowtype;
  v_paid numeric(12,2); v_remaining numeric(12,2); v_days integer;
  v_penalty numeric(12,2):=0; v_interest numeric(12,2):=0; v_cap numeric(12,2); v_total numeric(12,2); v_rate numeric;
begin
  select * into v_i from public.wm_loan_installments where tenant_id=p_tenant_id and id=p_installment_id;
  if not found then raise exception 'Parcela do empréstimo não encontrada.'; end if;
  select * into v_l from public.wm_loans where tenant_id=p_tenant_id and id=v_i.loan_id;
  if not found then raise exception 'Empréstimo não encontrado.'; end if;
  select coalesce(sum(amount),0) into v_paid from public.wm_loan_payments where tenant_id=p_tenant_id and installment_id=v_i.id;
  v_remaining:=greatest(round(v_i.amount-v_paid,2),0);
  v_days:=greatest((coalesce(p_as_of_date,current_date)-v_i.due_date)-v_l.grace_days,0);
  if v_days>0 and v_remaining>0 then
    v_penalty:=round(v_remaining*v_l.late_penalty_rate/100,2);
    v_rate:=v_l.late_interest_daily_rate/100;
    if v_rate>0 then
      if v_l.late_interest_compound then v_interest:=round(v_remaining*(power(1+v_rate,v_days)-1),2);
      else v_interest:=round(v_remaining*v_rate*v_days,2); end if;
    end if;
    v_cap:=round(v_i.amount*v_l.late_charge_cap_rate/100,2);
    if v_cap>=0 and v_penalty+v_interest>v_cap then
      if v_penalty>=v_cap then v_penalty:=v_cap; v_interest:=0;
      else v_interest:=greatest(round(v_cap-v_penalty,2),0); end if;
    end if;
  end if;
  v_total:=round(v_remaining+v_penalty+v_interest,2);
  return jsonb_build_object('installmentId',v_i.id,'loanId',v_l.id,'dueDate',v_i.due_date,'amount',v_i.amount,'paidAmount',v_paid,'remainingPrincipal',v_remaining,'daysLate',v_days,'latePenalty',v_penalty,'lateInterest',v_interest,'lateCharges',round(v_penalty+v_interest,2),'totalDue',v_total,'status',case when v_i.status='paid' or v_remaining<=0 then 'paid' else 'pending' end);
end; $$;

create or replace function public.wm_create_loan(
  p_tenant_id uuid,p_customer_id bigint,p_principal numeric,p_interest_rate numeric default 0,
  p_start_date date default current_date,p_first_due_date date default current_date,p_installments integer default 1,
  p_frequency text default 'unico',p_notes text default ''
) returns jsonb language plpgsql set search_path to 'public','pg_temp' as $$
declare
  v_customer public.wm_customers%rowtype; v_loan_id bigint; v_interest numeric(12,2); v_total numeric(12,2);
  v_base numeric(12,2); v_amount numeric(12,2); v_due date; v_i integer; v_policy public.wm_loan_policies%rowtype;
begin
  if p_tenant_id is null or p_customer_id is null then raise exception 'Cliente inválido.'; end if;
  if p_principal is null or p_principal <= 0 then raise exception 'Informe um valor de empréstimo válido.'; end if;
  if p_interest_rate is null or p_interest_rate < 0 then raise exception 'Informe uma taxa de juros válida.'; end if;
  if p_installments is null or p_installments < 1 or p_installments > 120 then raise exception 'Quantidade de parcelas inválida.'; end if;
  if p_frequency not in ('unico','semanal','quinzenal','mensal') then raise exception 'Periodicidade inválida.'; end if;
  if p_first_due_date is null or p_start_date is null then raise exception 'Informe as datas do empréstimo.'; end if;
  if p_frequency='unico' and p_installments<>1 then raise exception 'Empréstimo único deve ter 1 parcela.'; end if;
  select * into v_customer from public.wm_customers where tenant_id=p_tenant_id and id=p_customer_id;
  if not found then raise exception 'Cliente não encontrado.'; end if;
  insert into public.wm_loan_policies(tenant_id) values(p_tenant_id) on conflict (tenant_id) do nothing;
  select * into v_policy from public.wm_loan_policies where tenant_id=p_tenant_id;
  v_interest:=round(p_principal*p_interest_rate/100,2); v_total:=round(p_principal+v_interest,2); v_base:=round(v_total/p_installments,2);
  insert into public.wm_loans(tenant_id,customer_id,principal,interest_rate,interest_amount,total_amount,start_date,due_date,installments,frequency,status,notes,grace_days,late_penalty_rate,late_interest_daily_rate,late_interest_compound,late_charge_cap_rate)
  values(p_tenant_id,p_customer_id,round(p_principal,2),round(p_interest_rate,4),v_interest,v_total,p_start_date,p_first_due_date,p_installments,p_frequency,'active',coalesce(p_notes,''),v_policy.grace_days,v_policy.late_penalty_rate,v_policy.late_interest_daily_rate,v_policy.late_interest_compound,v_policy.late_charge_cap_rate)
  returning id into v_loan_id;
  for v_i in 1..p_installments loop
    if p_frequency='unico' then v_due:=p_first_due_date;
    elsif p_frequency='semanal' then v_due:=p_first_due_date+((v_i-1)*7);
    elsif p_frequency='quinzenal' then v_due:=p_first_due_date+((v_i-1)*15);
    else v_due:=(p_first_due_date+make_interval(months=>v_i-1))::date; end if;
    v_amount:=case when v_i<p_installments then v_base else round(v_total-(v_base*(p_installments-1)),2) end;
    insert into public.wm_loan_installments(tenant_id,loan_id,installment_number,due_date,amount) values(p_tenant_id,v_loan_id,v_i,v_due,v_amount);
  end loop;
  insert into public.wm_cash_entries(tenant_id,kind,category,description,amount,payment_method,occurred_at,source_type,source_id)
  values(p_tenant_id,'expense','Empréstimo concedido','Empréstimo para '||v_customer.name,round(p_principal,2),'dinheiro',p_start_date::timestamptz,'loan',v_loan_id);
  return jsonb_build_object('loanId',v_loan_id,'customerId',v_customer.id,'customerName',v_customer.name,'principal',round(p_principal,2),'interestRate',round(p_interest_rate,4),'interestAmount',v_interest,'totalAmount',v_total,'installments',p_installments,'firstDueDate',p_first_due_date,'status','active','policy',jsonb_build_object('graceDays',v_policy.grace_days,'latePenaltyRate',v_policy.late_penalty_rate,'lateInterestDailyRate',v_policy.late_interest_daily_rate,'lateInterestCompound',v_policy.late_interest_compound,'lateChargeCapRate',v_policy.late_charge_cap_rate));
end; $$;

create or replace function public.wm_record_loan_payment(
  p_tenant_id uuid,p_installment_id bigint,p_amount numeric,p_payment_method text default 'dinheiro',p_paid_at timestamptz default now(),p_notes text default ''
) returns jsonb language plpgsql set search_path to 'public','pg_temp' as $$
declare
  v_installment public.wm_loan_installments%rowtype; v_loan public.wm_loans%rowtype; v_customer public.wm_customers%rowtype;
  v_due jsonb; v_paid numeric(12,2); v_remaining numeric(12,2); v_payment_id bigint; v_cash_id bigint; v_status text; v_total_due numeric(12,2); v_msg text;
begin
  if p_amount is null or p_amount<=0 then raise exception 'Informe um valor de pagamento válido.'; end if;
  select * into v_installment from public.wm_loan_installments where tenant_id=p_tenant_id and id=p_installment_id for update;
  if not found then raise exception 'Parcela do empréstimo não encontrada.'; end if;
  select * into v_loan from public.wm_loans where tenant_id=p_tenant_id and id=v_installment.loan_id for update;
  if not found then raise exception 'Empréstimo não encontrado.'; end if;
  if v_loan.status='cancelled' then raise exception 'Este empréstimo está cancelado.'; end if;
  select * into v_customer from public.wm_customers where tenant_id=p_tenant_id and id=v_loan.customer_id;
  if not found then raise exception 'Cliente não encontrado.'; end if;
  select coalesce(sum(amount),0) into v_paid from public.wm_loan_payments where tenant_id=p_tenant_id and installment_id=v_installment.id;
  v_remaining:=round(v_installment.amount-v_paid,2);
  if v_remaining<=0 then raise exception 'Esta parcela já está quitada.'; end if;
  select public.wm_calculate_loan_installment_due(p_tenant_id,v_installment.id,coalesce(p_paid_at::date,current_date)) into v_due;
  v_total_due:=coalesce((v_due->>'totalDue')::numeric,v_remaining);
  if round(p_amount,2)>v_total_due+0.005 then
    v_msg:='O pagamento não pode ser maior que o total devido de '||to_char(v_total_due,'FM999999990.00')||'.';
    raise exception using message=v_msg;
  end if;
  insert into public.wm_loan_payments(tenant_id,loan_id,installment_id,customer_id,amount,payment_method,paid_at,notes)
  values(p_tenant_id,v_loan.id,v_installment.id,v_loan.customer_id,round(p_amount,2),coalesce(nullif(trim(p_payment_method),''),'dinheiro'),coalesce(p_paid_at,now()),coalesce(p_notes,'')||case when coalesce((v_due->>'lateCharges')::numeric,0)>0 then ' | Encargos por atraso: '||to_char((v_due->>'lateCharges')::numeric,'FM999999990.00') else '' end)
  returning id into v_payment_id;
  v_paid:=round(v_paid+round(p_amount,2),2); v_total_due:=round(v_total_due,2);
  if v_paid>=v_total_due-0.005 then update public.wm_loan_installments set status='paid',paid_at=coalesce(p_paid_at,now()) where id=v_installment.id and tenant_id=p_tenant_id; end if;
  if not exists(select 1 from public.wm_loan_installments li where li.tenant_id=p_tenant_id and li.loan_id=v_loan.id and li.status='pending') then
    update public.wm_loans set status='paid',updated_at=now() where tenant_id=p_tenant_id and id=v_loan.id; v_status:='paid';
  else v_status:='active'; end if;
  insert into public.wm_cash_entries(tenant_id,kind,category,description,amount,payment_method,occurred_at,source_type,source_id)
  values(p_tenant_id,'income','Recebimento de empréstimo','Parcela '||v_installment.installment_number||' — '||v_customer.name,round(p_amount,2),coalesce(nullif(trim(p_payment_method),''),'dinheiro'),coalesce(p_paid_at,now()),'loan_payment',v_payment_id) returning id into v_cash_id;
  return jsonb_build_object('loanPaymentId',v_payment_id,'cashEntryId',v_cash_id,'loanId',v_loan.id,'installmentId',v_installment.id,'customerId',v_customer.id,'customerName',v_customer.name,'installmentNumber',v_installment.installment_number,'installmentAmount',v_installment.amount,'paidAmount',round(p_amount,2),'paidTotal',v_paid,'remainingAmount',greatest(v_total_due-v_paid,0),'dueDate',v_installment.due_date,'paidAt',coalesce(p_paid_at,now()),'paymentMethod',coalesce(nullif(trim(p_payment_method),''),'dinheiro'),'daysLate',coalesce((v_due->>'daysLate')::integer,0),'latePenalty',coalesce((v_due->>'latePenalty')::numeric,0),'lateInterest',coalesce((v_due->>'lateInterest')::numeric,0),'lateCharges',coalesce((v_due->>'lateCharges')::numeric,0),'totalDue',v_total_due,'status',v_status);
end; $$;

revoke all on function public.wm_get_loan_policy(uuid),public.wm_upsert_loan_policy(uuid,integer,numeric,numeric,boolean,numeric,integer[]) from public,anon,authenticated;
grant execute on function public.wm_get_loan_policy(uuid),public.wm_upsert_loan_policy(uuid,integer,numeric,numeric,boolean,numeric,integer[]) to service_role;
revoke all on function public.wm_calculate_loan_installment_due(uuid,bigint,date) from public,anon,authenticated;
grant execute on function public.wm_calculate_loan_installment_due(uuid,bigint,date) to service_role;

commit;