begin;

create table if not exists public.wm_receivable_payments (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.wm_tenants(id) on delete restrict,
  receivable_id bigint not null references public.wm_receivables(id) on delete restrict,
  customer_id bigint not null references public.wm_customers(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  payment_method text not null default 'dinheiro',
  paid_at timestamptz not null default now(),
  notes text not null default '',
  entry_type text not null default 'manual' check (entry_type in ('manual','legacy')),
  created_at timestamptz not null default now()
);

alter table public.wm_receivable_payments enable row level security;
revoke all on public.wm_receivable_payments from anon, authenticated;
grant all on public.wm_receivable_payments to service_role;

create index if not exists wm_receivable_payments_tenant_paid_idx
  on public.wm_receivable_payments(tenant_id, paid_at desc);
create index if not exists wm_receivable_payments_receivable_idx
  on public.wm_receivable_payments(receivable_id, paid_at desc);
create unique index if not exists wm_receivable_payments_legacy_once_idx
  on public.wm_receivable_payments(receivable_id)
  where entry_type = 'legacy';

insert into public.wm_receivable_payments
  (tenant_id, receivable_id, customer_id, amount, payment_method, paid_at, notes, entry_type)
select r.tenant_id, r.id, r.customer_id, r.amount, 'legacy',
       coalesce(r.paid_at, now()),
       'Recebimento histórico migrado automaticamente.',
       'legacy'
from public.wm_receivables r
where r.status = 'paid'
  and r.paid_at is not null
  and not exists (
    select 1 from public.wm_receivable_payments p
    where p.receivable_id = r.id
      and p.entry_type = 'legacy'
  );

create or replace function public.wm_record_receivable_payment(
  p_tenant_id uuid,
  p_receivable_id bigint,
  p_amount numeric,
  p_payment_method text default 'dinheiro',
  p_paid_at timestamptz default now(),
  p_notes text default ''
) returns jsonb
language plpgsql
set search_path to 'public','pg_temp'
as $$
declare
  v_receivable public.wm_receivables%rowtype;
  v_customer public.wm_customers%rowtype;
  v_payment_id bigint;
  v_cash_id bigint;
  v_paid_total numeric(12,2);
  v_remaining numeric(12,2);
  v_status text;
  v_paid_at timestamptz := coalesce(p_paid_at, now());
  v_method text := nullif(trim(coalesce(p_payment_method, '')), '');
begin
  if v_method is null then v_method := 'dinheiro'; end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'Informe um valor de pagamento válido.';
  end if;

  select * into v_receivable
  from public.wm_receivables
  where tenant_id = p_tenant_id and id = p_receivable_id
  for update;

  if not found then raise exception 'Parcela não encontrada.'; end if;

  select * into v_customer
  from public.wm_customers
  where tenant_id = p_tenant_id and id = v_receivable.customer_id;

  if not found then raise exception 'Cliente da parcela não encontrado.'; end if;

  select coalesce(sum(amount),0) into v_paid_total
  from public.wm_receivable_payments
  where tenant_id = p_tenant_id and receivable_id = v_receivable.id;

  v_remaining := round(v_receivable.amount - v_paid_total, 2);

  if v_remaining <= 0 then raise exception 'Esta parcela já está quitada.'; end if;
  if round(p_amount,2) > v_remaining then
    raise exception 'O pagamento não pode ser maior que o saldo da parcela.';
  end if;

  insert into public.wm_receivable_payments
    (tenant_id, receivable_id, customer_id, amount, payment_method, paid_at, notes, entry_type)
  values
    (p_tenant_id, v_receivable.id, v_receivable.customer_id,
     round(p_amount,2), v_method, v_paid_at, coalesce(p_notes,''), 'manual')
  returning id into v_payment_id;

  v_paid_total := round(v_paid_total + round(p_amount,2), 2);
  v_remaining := round(v_receivable.amount - v_paid_total, 2);
  v_status := case when v_remaining <= 0 then 'paid' else 'pending' end;

  update public.wm_receivables
  set status = v_status,
      paid_at = case when v_status = 'paid' then v_paid_at else paid_at end
  where tenant_id = p_tenant_id and id = v_receivable.id;

  insert into public.wm_cash_entries
    (tenant_id, kind, category, description, amount, payment_method, occurred_at, source_type, source_id)
  values
    (p_tenant_id, 'income', 'Recebimento de cliente',
     'Recebimento da parcela ' || v_receivable.installment_number || ' — ' || v_customer.name,
     round(p_amount,2), v_method, v_paid_at, 'receivable_payment', v_payment_id)
  returning id into v_cash_id;

  return jsonb_build_object(
    'paymentId', v_payment_id, 'cashEntryId', v_cash_id,
    'receivableId', v_receivable.id, 'saleId', v_receivable.sale_id,
    'customerId', v_customer.id, 'customerName', v_customer.name,
    'customerPhone', v_customer.phone, 'installmentNumber', v_receivable.installment_number,
    'installmentAmount', round(v_receivable.amount,2), 'paidAmount', round(p_amount,2),
    'paidTotal', v_paid_total, 'remainingAmount', greatest(v_remaining,0),
    'dueDate', v_receivable.due_date, 'paidAt', v_paid_at,
    'paymentMethod', v_method, 'status', v_status
  );
end;
$$;

revoke all on function public.wm_record_receivable_payment(uuid,bigint,numeric,text,timestamptz,text) from public, anon, authenticated;
grant execute on function public.wm_record_receivable_payment(uuid,bigint,numeric,text,timestamptz,text) to service_role;

commit;