create table if not exists public.wm_store_settings (
  id boolean primary key default true check (id),
  store_name text not null default 'WM Vendas',
  pix_key text not null default '',
  pix_holder_name text not null default 'Walquiria Maia',
  pix_city text not null default 'SAO PAULO',
  whatsapp text not null default '',
  store_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.wm_store_settings (id) values (true) on conflict (id) do nothing;

create table if not exists public.wm_store_orders (
  id bigint generated by default as identity primary key,
  public_id uuid not null default gen_random_uuid() unique,
  customer_name text not null,
  phone text not null,
  delivery_type text not null default 'retirada' check (delivery_type in ('retirada','entrega')),
  address text not null default '',
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  status text not null default 'awaiting_payment' check (status in ('awaiting_payment','paid','preparing','completed','cancelled')),
  pix_payload text,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wm_store_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.wm_store_orders(id) on delete cascade,
  product_id bigint not null references public.wm_products(id),
  product_name text not null,
  unit_price numeric(12,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(12,2) not null check (line_total >= 0)
);

create index if not exists wm_store_orders_status_created_idx on public.wm_store_orders(status, created_at desc);
create index if not exists wm_store_order_items_order_idx on public.wm_store_order_items(order_id);

create table if not exists public.wm_store_order_attempts (
  id bigint generated by default as identity primary key,
  client_key text not null,
  attempted_at timestamptz not null default now()
);
create index if not exists wm_store_order_attempts_client_time_idx on public.wm_store_order_attempts(client_key, attempted_at desc);

alter table public.wm_store_settings enable row level security;
alter table public.wm_store_orders enable row level security;
alter table public.wm_store_order_items enable row level security;
alter table public.wm_store_order_attempts enable row level security;
revoke all on public.wm_store_settings from anon, authenticated;
revoke all on public.wm_store_orders from anon, authenticated;
revoke all on public.wm_store_order_items from anon, authenticated;
revoke all on public.wm_store_order_attempts from anon, authenticated;

create or replace function public.wm_create_store_order(
  p_customer_name text,
  p_phone text,
  p_delivery_type text,
  p_address text,
  p_items jsonb
) returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_order_id bigint;
  v_public_id uuid;
  v_item jsonb;
  v_product public.wm_products%rowtype;
  v_quantity integer;
  v_total numeric(12,2) := 0;
begin
  if length(trim(coalesce(p_customer_name,''))) < 2 then raise exception 'Informe seu nome.'; end if;
  if length(regexp_replace(coalesce(p_phone,''), '\D', '', 'g')) < 10 then raise exception 'Informe um WhatsApp válido.'; end if;
  if p_delivery_type not in ('retirada','entrega') then raise exception 'Forma de entrega inválida.'; end if;
  if p_delivery_type = 'entrega' and length(trim(coalesce(p_address,''))) < 5 then raise exception 'Informe o endereço de entrega.'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 30 then raise exception 'Carrinho inválido.'; end if;

  insert into public.wm_store_orders(customer_name, phone, delivery_type, address)
  values (trim(p_customer_name), regexp_replace(p_phone, '\D', '', 'g'), p_delivery_type, trim(coalesce(p_address,'')))
  returning id, public_id into v_order_id, v_public_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_quantity := greatest(0, least(99, coalesce((v_item->>'quantity')::integer,0)));
    if v_quantity < 1 then raise exception 'Quantidade inválida.'; end if;
    select * into v_product from public.wm_products where id = (v_item->>'productId')::bigint for update;
    if not found then raise exception 'Produto não encontrado.'; end if;
    if v_product.stock < v_quantity then raise exception 'Estoque insuficiente para %.', v_product.name; end if;
    insert into public.wm_store_order_items(order_id, product_id, product_name, unit_price, quantity, line_total)
    values (v_order_id, v_product.id, v_product.name, v_product.sale_price, v_quantity, v_product.sale_price * v_quantity);
    update public.wm_products set stock = stock - v_quantity, updated_at = now() where id = v_product.id;
    v_total := v_total + (v_product.sale_price * v_quantity);
  end loop;

  update public.wm_store_orders set subtotal = v_total, total = v_total, updated_at = now() where id = v_order_id;
  return jsonb_build_object('id', v_order_id, 'publicId', v_public_id, 'total', v_total);
end;
$$;

revoke all on function public.wm_create_store_order(text,text,text,text,jsonb) from public, anon, authenticated;
grant execute on function public.wm_create_store_order(text,text,text,text,jsonb) to service_role;

create or replace function public.wm_cancel_store_order(p_order_id bigint)
returns void
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare v_status text; v_item record;
begin
  select status into v_status from public.wm_store_orders where id = p_order_id for update;
  if not found then raise exception 'Pedido não encontrado.'; end if;
  if v_status <> 'awaiting_payment' then raise exception 'Somente pedidos aguardando pagamento podem ser cancelados.'; end if;
  for v_item in select product_id, quantity from public.wm_store_order_items where order_id = p_order_id
  loop
    update public.wm_products set stock = stock + v_item.quantity, updated_at = now() where id = v_item.product_id;
  end loop;
  update public.wm_store_orders set status = 'cancelled', updated_at = now() where id = p_order_id;
end;
$$;
revoke all on function public.wm_cancel_store_order(bigint) from public, anon, authenticated;
grant execute on function public.wm_cancel_store_order(bigint) to service_role;
