-- Gestão financeira, reservas seguras e índices de desempenho.
create table if not exists public.wm_cash_entries (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.wm_tenants(id) on delete restrict,
  kind text not null check (kind in ('income','expense')),
  category text not null default 'Outros',
  description text not null,
  amount numeric not null check (amount > 0),
  payment_method text not null default 'other',
  occurred_at timestamptz not null default now(),
  source_type text,
  source_id bigint,
  created_at timestamptz not null default now()
);
alter table public.wm_cash_entries enable row level security;
create index if not exists wm_cash_entries_tenant_occurred_idx on public.wm_cash_entries(tenant_id,occurred_at desc);
create index if not exists wm_cash_entries_tenant_kind_idx on public.wm_cash_entries(tenant_id,kind);

create or replace function public.wm_create_store_order_v2(
  p_tenant_id uuid,p_customer_name text,p_phone text,p_delivery_type text,
  p_address text,p_payment_method text,p_items jsonb
) returns jsonb language plpgsql set search_path to 'public','pg_temp' as $$
declare
  v_order_id bigint; v_public_id uuid; v_status text; v_item jsonb;
  v_product public.wm_products%rowtype; v_quantity integer; v_total numeric(12,2):=0;
begin
  if p_tenant_id is null then raise exception 'Loja inválida.'; end if;
  if length(trim(coalesce(p_customer_name,'')))<2 then raise exception 'Informe seu nome.'; end if;
  if length(regexp_replace(coalesce(p_phone,''),'\D','','g'))<10 then raise exception 'Informe um WhatsApp válido.'; end if;
  if p_delivery_type not in ('retirada','entrega') then raise exception 'Forma de entrega inválida.'; end if;
  if p_delivery_type='entrega' and length(trim(coalesce(p_address,'')))<5 then raise exception 'Informe o endereço de entrega.'; end if;
  if p_payment_method not in ('pix','reservation','deposit') then raise exception 'Forma de pagamento inválida.'; end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 or jsonb_array_length(p_items)>30 then raise exception 'Cesta inválida.'; end if;
  v_status:=case when p_payment_method='reservation' then 'awaiting_approval' else 'awaiting_payment' end;
  insert into public.wm_store_orders(tenant_id,customer_name,phone,delivery_type,address,payment_method,status,reservation_expires_at)
  values(p_tenant_id,trim(p_customer_name),regexp_replace(p_phone,'\D','','g'),p_delivery_type,trim(coalesce(p_address,'')),p_payment_method,v_status,now()+interval '24 hours')
  returning id,public_id into v_order_id,v_public_id;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity:=greatest(0,least(99,coalesce((v_item->>'quantity')::integer,0)));
    if v_quantity<1 then raise exception 'Quantidade inválida.'; end if;
    select * into v_product from public.wm_products where id=(v_item->>'productId')::bigint and tenant_id=p_tenant_id for update;
    if not found then raise exception 'Produto não encontrado.'; end if;
    if v_product.stock<v_quantity then raise exception 'Estoque insuficiente para %.',v_product.name; end if;
    insert into public.wm_store_order_items(tenant_id,order_id,product_id,product_name,unit_price,quantity,line_total)
    values(p_tenant_id,v_order_id,v_product.id,v_product.name,v_product.sale_price,v_quantity,v_product.sale_price*v_quantity);
    update public.wm_products set stock=stock-v_quantity,updated_at=now() where id=v_product.id and tenant_id=p_tenant_id;
    v_total:=v_total+(v_product.sale_price*v_quantity);
  end loop;
  update public.wm_store_orders set subtotal=v_total,total=v_total,updated_at=now() where id=v_order_id and tenant_id=p_tenant_id;
  return jsonb_build_object('id',v_order_id,'publicId',v_public_id,'total',v_total,'status',v_status,'paymentMethod',p_payment_method);
end $$;

create or replace function public.wm_expire_store_reservations(p_tenant_id uuid)
returns integer language plpgsql set search_path to 'public','pg_temp' as $$
declare v_order record; v_item record; v_count integer:=0;
begin
  for v_order in select id from public.wm_store_orders
    where tenant_id=p_tenant_id and status in ('awaiting_payment','awaiting_approval','reserved') and reservation_expires_at<now()
    for update skip locked
  loop
    for v_item in select product_id,quantity from public.wm_store_order_items where order_id=v_order.id loop
      update public.wm_products set stock=stock+v_item.quantity,updated_at=now() where id=v_item.product_id and tenant_id=p_tenant_id;
    end loop;
    update public.wm_store_orders set status='cancelled',delivery_status='cancelled',updated_at=now() where id=v_order.id and tenant_id=p_tenant_id;
    v_count:=v_count+1;
  end loop;
  return v_count;
end $$;
revoke all on function public.wm_expire_store_reservations(uuid) from public,anon,authenticated;

create index if not exists wm_payment_requests_customer_idx on public.wm_payment_requests(customer_id);
create index if not exists wm_payment_requests_receivable_idx on public.wm_payment_requests(receivable_id);
create index if not exists wm_secure_links_customer_idx on public.wm_secure_links(customer_id);
create index if not exists wm_secure_links_receivable_idx on public.wm_secure_links(receivable_id);
create index if not exists wm_store_order_items_product_idx on public.wm_store_order_items(product_id);
create index if not exists wm_store_orders_customer_idx on public.wm_store_orders(customer_id);
create index if not exists wm_tenant_members_user_idx on public.wm_tenant_members(user_id);
